export const errorMiddleware = (err, req, res, next) => {

    err.message || (err.message = "Internal Server Error");
    err.statusCode || (err.statusCode = 500);


    if (err.name == 'CastError')
        err.message = "invalid id";
    if (err.name === 'MongoServerError')
        err.message = `A document with the same field already exists`;


    return res.status(err.statusCode).json({
        success: false,
        message: err.message,
    });
};


export const TryCatch = (func) => (req, res, next) => {
    return Promise.resolve(func(req, res, next)).catch(next);
};

